#!/bin/bash

#  _       _ _   
# (_)_ __ (_) |_ 
# | | '_ \| | __|
# | | | | | | |_ 
# |_|_| |_|_|\__|
# ps: all fontart generated by figlet               
# import all functions and init the env for ubuntu
source ./lib/*.sh
check-root
check-config
check-ubuntu
env-ubuntu